spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/full
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB